[general]
callsign="ON4MOD-1"
tx_queue_size=64
rx_queue_size=64

[general.net_if]
name="m17d"
ip="172.16.0.1"
MTU=822

[radio]
tx_frequency=433475000
rx_frequency=433475000
k_mod=3.75
ppm=-21

[[peers]]
callsign="ON4MOD-2"
ip="172.16.0.8"
routes=["172.16.0.8/29"]

[[peers]]
callsign="ON4MOD-3"
ip="172.16.0.16"
routes=["172.16.0.16/29"]

[sdrnode]
spi_dev="/dev/spidev1.0"
i2s_rx = "default:GDisDACout"
i2s_tx = "default:GDisDACout"
